# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bK3tSk0792TKEJ-dl2CrKLf-hD8t_60M
"""

import time
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# ==========================================
# 1. KONFIGURASI LOKASI & PARAMETER SEAWATER INTAKE
# ==========================================
LAT_GRATI = -7.644317   # S 07°38.659'
LON_GRATI = 113.027350  # E 113°01.641'
TIMEZONE = "Asia/Jakarta"

# Batas Operasional Water Intake PLTGU Grati (dapat disesuaikan dengan MSL/CD lokal)
CRITICAL_LOW_LEVEL = 0.5   # Meter (Potensi Pump Cavitation / Trip)
CRITICAL_HIGH_LEVEL = 2.8  # Meter (Potensi Overflow Intake Channel)

# ==========================================
# 2. SINTESIS & PERSIAPAN DATA LATIKAN (TIDE + METEOROLOGI)
# ==========================================
def generate_training_data(days=180):
    """
    Membuat dataset historis gabungan komponen pasang surut Diurnal (Probolinggo)
    dan dampak efek angin/tekanan udara untuk melatih model ML.
    """
    np.random.seed(42)
    start_date = datetime.now() - timedelta(days=days)
    dates = [start_date + timedelta(hours=i) for i in range(days * 24)]

    df = pd.DataFrame({"datetime": dates})
    df["hour"] = df["datetime"].dt.hour
    df["dayofyear"] = df["datetime"].dt.dayofyear

    # Komponen Pasang Surut Astronomis Utama (Diurnal K1, O1 & Semidiurnal M2, S2)
    t = np.arange(len(df))
    harmonic_k1 = 0.9 * np.sin(2 * np.pi * t / 23.93)
    harmonic_o1 = 0.6 * np.sin(2 * np.pi * t / 25.82 + 0.5)
    harmonic_m2 = 0.3 * np.cos(2 * np.pi * t / 12.42)
    msl_base = 1.5  # Mean Sea Level (Meter)

    df["astronomical_tide"] = msl_base + harmonic_k1 + harmonic_o1 + harmonic_m2

    # Fitur Meteorologi (Di-generate untuk simulasi training set)
    df["pressure_hpa"] = 1010 + 5 * np.sin(2 * np.pi * t / (24 * 7)) + np.random.normal(0, 1.5, len(df))
    df["wind_speed_m_s"] = np.abs(4 + 3 * np.cos(2 * np.pi * t / 24) + np.random.normal(0, 2, len(df)))
    df["wind_direction_deg"] = (45 + np.random.normal(0, 30, len(df))) % 360  # Angin laut utara/timur laut

    # Formulasi Storm Surge (Pengaruh Tekanan & Angin terhadap elevasi air laut)
    # Inverse Barometer Effect (~1 cm per 1 hPa drop below 1013.25)
    surge_pressure = (1013.25 - df["pressure_hpa"]) * 0.01
    surge_wind = (df["wind_speed_m_s"] ** 1.8) * 0.003 * np.cos(np.radians(df["wind_direction_deg"] - 45))

    # Ketinggian Air Aktual Intake (Target Prediksi)
    noise = np.random.normal(0, 0.03, len(df))
    df["actual_water_level"] = df["astronomical_tide"] + surge_pressure + surge_wind + noise

    return df

# ==========================================
# 3. PELATIHAN MODEL MACHINE LEARNING
# ==========================================
class WaterLevelMLModel:
    def __init__(self):
        self.model = GradientBoostingRegressor(n_estimators=150, learning_rate=0.08, max_depth=5, random_state=42)
        self.features = ["hour", "dayofyear", "astronomical_tide", "pressure_hpa", "wind_speed_m_s", "wind_direction_deg"]

    def train(self, df):
        X = df[self.features]
        y = df["actual_water_level"]

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)
        self.model.fit(X_train, y_train)

        preds = self.model.predict(X_test)
        rmse = np.sqrt(mean_squared_error(y_test, preds))
        r2 = r2_score(y_test, preds)

        print("=== EVALUASI MODEL MACHINE LEARNING ===")
        print(f"Root Mean Squared Error (RMSE): {rmse:.4f} meter")
        print(f"R-squared (R2 Score)          : {r2:.4f}\n")

    def predict(self, feature_dict):
        df_input = pd.DataFrame([feature_dict])[self.features]
        return self.model.predict(df_input)[0]

# ==========================================
# 4. KONEKSI DATA REALTIME METEOROLOGI (API)
# ==========================================
def fetch_realtime_weather_data(lat, lon):
    """
    Mengambil data cuaca dan marin realtime dari Open-Meteo API
    """
    url = f"https://api.open-meteo.com/v1/forecast?latitude={lat}&longitude={lon}&current=surface_pressure,wind_speed_10m,wind_direction_10m&timezone=Asia%2FJakarta"
    try:
        response = requests.get(url, timeout=10)
        data = response.json()
        current = data.get("current", {})

        return {
            "pressure_hpa": current.get("surface_pressure", 1011.0),
            "wind_speed_m_s": current.get("wind_speed_10m", 3.5) / 3.6, # Convert km/h to m/s
            "wind_direction_deg": current.get("wind_direction_10m", 60.0)
        }
    except Exception as e:
        print(f"[WARNING] Gagal mengambil data API: {e}. Menggunakan nilai fallback.")
        return {"pressure_hpa": 1011.0, "wind_speed_m_s": 3.0, "wind_direction_deg": 45.0}

def compute_astronomical_tide(dt):
    """
    Perhitungan perkiraan pasang surut harian tunggal (diurnal) berdasarkan siklus astronomis lokal.
    """
    t_hours = dt.timestamp() / 3600.0
    msl = 1.5
    k1 = 0.9 * np.sin(2 * np.pi * t_hours / 23.93)
    o1 = 0.6 * np.sin(2 * np.pi * t_hours / 25.82 + 0.5)
    m2 = 0.3 * np.cos(2 * np.pi * t_hours / 12.42)
    return msl + k1 + o1 + m2

# ==========================================
# 5. EXECUTION PIPELINE & MONITORING REALTIME
# ==========================================
def run_realtime_monitoring(ml_model, iterations=5, interval_seconds=3):
    """
    Menjalankan simulasi monitoring realtime dan forecasting 6 jam ke depan.
    """
    print(f"--- STARTING REALTIME WATER INTAKE MONITORING ---")
    print(f"Lokasi: PLTGU Grati ({LAT_GRATI}, {LON_GRATI})\n")

    history_time = []
    history_predicted = []

    for i in range(iterations):
        now = datetime.now()
        weather = fetch_realtime_weather_data(LAT_GRATI, LON_GRATI)
        astro_tide = compute_astronomical_tide(now)

        input_data = {
            "hour": now.hour,
            "dayofyear": now.timetuple().tm_yday,
            "astronomical_tide": astro_tide,
            "pressure_hpa": weather["pressure_hpa"],
            "wind_speed_m_s": weather["wind_speed_m_s"],
            "wind_direction_deg": weather["wind_direction_deg"]
        }

        predicted_level = ml_model.predict(input_data)
        history_time.append(now.strftime("%H:%M:%S"))
        history_predicted.append(predicted_level)

        # Cek Status Peringatan Dini
        status = "NORMAL"
        if predicted_level <= CRITICAL_LOW_LEVEL:
            status = "CRITICAL LOW (RISK CAVITATION)"
        elif predicted_level >= CRITICAL_HIGH_LEVEL:
            status = "CRITICAL HIGH (RISK OVERFLOW)"

        print(f"[{now.strftime('%Y-%m-%d %H:%M:%S')}] Prediksi Intake: {predicted_level:.3f} m | Astro Tide: {astro_tide:.3f} m | Press: {weather['pressure_hpa']} hPa | Status: {status}")

        time.sleep(interval_seconds)

    # Plotting Grafik Monitoring
    plot_realtime_dashboard(history_time, history_predicted)

def plot_realtime_dashboard(times, levels):
    plt.figure(figsize=(10, 4.5))
    plt.plot(times, levels, marker='o', color='b', linewidth=2, label='ML Predicted Water Level')
    plt.axhline(y=CRITICAL_HIGH_LEVEL, color='r', linestyle='--', label='High Alarm Limit (2.8m)')
    plt.axhline(y=CRITICAL_LOW_LEVEL, color='orange', linestyle='--', label='Low Alarm Limit (0.5m)')

    plt.title('Realtime Sea Water Intake Level - PLTGU Grati (Pasuruan)', fontsize=12)
    plt.xlabel('Waktu (WIB)')
    plt.ylabel('Ketinggian Air (Meter)')
    plt.grid(True, linestyle=':', alpha=0.6)
    plt.legend(loc='upper right')
    plt.tight_layout()
    plt.show()

# ==========================================
# MAIN MAIN PROGRAM
# ==========================================
if __name__ == "__main__":
    # 1. Generate Data & Train Model
    print("Memuat data histori & melatih model Machine Learning...")
    df_train = generate_training_data(days=180)
    ml_system = WaterLevelMLModel()
    ml_system.train(df_train)

    # 2. Jalankan Monitoring Realtime
    run_realtime_monitoring(ml_system, iterations=5, interval_seconds=2)